# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  backend:
    build:
      context: "/Users/mohamedabdelmeged/Desktop/training/dotnet/CSharpTopics/Hashing"
      dockerfile: "Dockerfile.dev"
      args:
        BUILD_CONFIGURATION: "Debug"
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57401"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57401"
    volumes:
    - "/Users/mohamedabdelmeged/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/mohamedabdelmeged/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2026_1_14_20_24_30:/var/opt/JetBrains/RiderDebuggerTools:rw"
