version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "bash init.sh"
    working_dir: /src
    environment:
      - ASPNETCORE_URLS:http://+:5001
      - ASPNETCORE_ENVIRONMENT:Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5001:5001"
    volumes:
      - .:/src
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database-app
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    healthcheck:
      test: >
        /opt/mssql-tools18/bin/sqlcmd
        -C
        -S localhost
        -U sa
        -P 'YourStrong!Passw0rd'
        -Q 'SELECT 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database-data:/var/opt/mssql

volumes:
  database-data: